// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyquULSSz0VTLy6_Af9wPui2FhmRFijok',
    appId: '1:841888310723:web:db1ad5662fdd1292998976',
    messagingSenderId: '841888310723',
    projectId: 'ecommerce-firebase-afcae',
    authDomain: 'ecommerce-firebase-afcae.firebaseapp.com',
    storageBucket: 'ecommerce-firebase-afcae.firebasestorage.app',
    measurementId: 'G-9JEX6F18ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wUBZG0CjTha0oV3d868jyTHLDyfEAfo',
    appId: '1:841888310723:android:322be5f8103ae773998976',
    messagingSenderId: '841888310723',
    projectId: 'ecommerce-firebase-afcae',
    storageBucket: 'ecommerce-firebase-afcae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSYYF3rZiPpiH1qMYrJk4B8g3jPayaDN4',
    appId: '1:841888310723:ios:9184bad826da6503998976',
    messagingSenderId: '841888310723',
    projectId: 'ecommerce-firebase-afcae',
    storageBucket: 'ecommerce-firebase-afcae.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSYYF3rZiPpiH1qMYrJk4B8g3jPayaDN4',
    appId: '1:841888310723:ios:9184bad826da6503998976',
    messagingSenderId: '841888310723',
    projectId: 'ecommerce-firebase-afcae',
    storageBucket: 'ecommerce-firebase-afcae.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyquULSSz0VTLy6_Af9wPui2FhmRFijok',
    appId: '1:841888310723:web:98667ea5ae59db0d998976',
    messagingSenderId: '841888310723',
    projectId: 'ecommerce-firebase-afcae',
    authDomain: 'ecommerce-firebase-afcae.firebaseapp.com',
    storageBucket: 'ecommerce-firebase-afcae.firebasestorage.app',
    measurementId: 'G-NP5D0RVGME',
  );
}
